### PR TITLE
Fix NOS Idle trigger and add support for CPU1 throttle

### PR DESCRIPTION
**Pull request by wschaub**
This commit corrects the check for CPU being in the idle package.
The check should be for if ! in monitor mode since the idle package does
not run in monitor mode.

In addition, this commit adds code to the CPU1 thread loop to check for
the idle package being in CPU1 and the number of times it's seen the
idle package in CPU1 and idles based on the global settings of the
trottle.

### CODE REVIEW

**Review by kej715 — CHANGES_REQUESTED** [review]
Hi  William,

The following changes are requested:

1. The DtCyber coding standard calls for variable names to begin with a lower case letter and use camel case. Please change names like NOSIdle to nosIdle, idletrigger to idleTrigger, idletime to idleTime, etc.
2. busyFlag should not be defined as a global variable. It is used only within a loop within the function "main", so it ought to be defined as a local variable there.
3. Variables idlecycles and cp1idlecycles should be defined as an element of the CpuContext structure instead of being defined as independent global variables. They can then be referenced as CPU-dependent properties, i.e., "activeCpu->idleCycles".

We should also start thinking about how further generalize this in the future, as it's currently specific to NOS. For example, perhaps a new cyber.ini directive should be added for specifying the operating system that will be running, and this could select OS-specific code for detecting an OS-specific idle loop. Also, it would probably be worthwhile to recognize "idle" as a top-level cyber.ini directive in addition to supporting it as an operator command.

**Comment by wschaub** [comment]
Sounds good, my original incarnation of this code has support for cyber.ini so I can re-use some of that. 

Do we want to keep the #ifdefs when I refactor?
if yes do I need to #ifdef the additions to the CPU context? 

 Assuming the other OS versions can be detected by P and FL values it shouldn't be hard to also set that in cyber.ini as well or provide some presets by name. 


I also have in my mind that it might shave some host CPU cycles off if we can detect idle PPs and skip over them until their input register becomes non zero. I just never could think of a good non invasive way to handle that or preserve PP state while "skipping" a PP.  I have studied the NOS 2.8.7 PP idle loop enough that I'm sure I could spot it.  since we are thinking about
generalizing things we might come up with a way to specify where to find needed pointers in low core in cyber.ini  if we want to go down that road. 

I will make idle settable by cyber.ini and see if I can make the OS type settable for more than just NOS 2.8.7, I have some NOS/BE 1.4 source code I can examine as well as KRONOS and NOS1.3.  If you have information on how the idle package is handled on HUSTLER that would be good to look at as well.

**Comment by wschaub** [comment]
KRONOS 2.1 - NOS 2.8.7 P = 2 FL = 5
KRONOS1/MACE  P = 2 FL =3

I think this is the idle loop for NOS/BE from CMR in PL1A  it should be P = 2 FL = 3
  
  ```
                                      **        IDLEIT   A USER MODE PROGRAM EXECUTED BY AN IDLE CPU
                                        *         ------   -------------------------------------------
                                        * 
                                        *         THE REFERENCE ADDRESS USED IN THIS EXCHANGE PACKAGE IS
                                        *         EQUAL TO IDLERA 
  
             1                                    BSS    0
                                   0    IDLERA    EQU    *-1               REFERENCE ADDRESS OF IDLE PROGRAM
             1                                    LOC    1
             1                     1              BSSZ   1                 RA+1 IS ALWAYS ZERO
             2                          IDLEIT    BSS    0                 IDLE LOOP
             2  0400000002                        EQ     IDLEIT 
             3                                    LOC    *O 

```

**Comment by wschaub** [comment]
I've cleaned up the code styling and removed the HUSTLER support because I don't have a full understanding of how to do it safely. 

Doing it on a single CPU system safely may be possible but it's probably better to leave it out for  now. 

This latest update should provide good throttling for both CPUs for NOS and possibly MACE and NOS/BE. (I ran the TUB ready to run pkg and saw it throttle but haven't explored it more in depth)

**Review by kej715 — APPROVED** [review]
Looks GREAT!

**Pull request merged**
