### PR TITLE
CCI emulation for DtCyber (mode3 terminals only)

### PR DESCRIPTION
**Pull request by bug400**
This PR enables DtCyber to run NOS/BE with multi terminal INTERCOM instead of single terminal RDF. 

See CCI.md for details.

### CODE REVIEW

**Review by kej715 — APPROVED** [review]

**Comment by kej715** [comment]
Excellent work! It's so very valuable to have CCI emulation in DtCyber.

**Comment by kej715** [comment]
Hi Joachim. Will you be making available a ready-to-run NOS/BE package that includes the HCP definition in the CMR deck, and precompiled configuration for INTERCOM? I would -love- to be able to try this new feature myself, but my NOS/BE experience is nil, and I'm a little lazy, so it would be very helpful to have a ready-to-run package. :-)

**Comment by bug400** [comment]
Hi Kevin, I'll be happy to have a preliminary version ready tomorrow.

**Comment by bug400** [comment]
Hi Kevin, a ready to run NOS/BE-Intercom system (EM and non EM version) can be downloaded [here](https://c.gmx.net/@317223139362739640/x5I8sD4-SeWbKRHP0UqtMQ).

This download link will be removed as soon as the NOS/BE material on the retro1.org website is updated.

If the directory NOSBE-INTERCOM is not installed in the DtCyber folder, the environment varible DTCYBER must
be set to the path for that directory.

Before starting NOS/BE for the first time, the following steps must be carried out:

* compile the lpt2pdf.c program in the lpt2pdf folder
* modify the path to the DtCyber webterm folder for "httpRoot" in webterm/config.json

To start NOS/BE without EM run:

     ./dtcyber nosbe (Linux) or dtcyber nosbe (Windows)

and with EM:

     ./dtcyber nosbe-em (Linux) or dtcyber nosbe-em (Windows)

INTERCOM needs a while to download the firmware to the HCP. The system is ready for log in (telnet port 6610), if the
message "1ND CHANNEL 07 INITIALIZED" appears on the operator console.

Note: Backspace is Ctrl-h

You find additional information on the [now outdated NOS/BE rtr guide](https://codex.retro1.org/cdc:nosbe:use_a_ready_to_run_nos_be_l_712_system).

**Comment by kej715** [comment]
Hi Joachim,

Thank you VERY much! It installs easily and works very well.

cheers,
Kevin

**Pull request merged**
